config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :meetings
    devise_for :users
    root 'pages#home'
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :creator, foreign_key: 'user_id', class_name: :User
  has_many :members
  has_many :users, through: :members

  validates :start_time, :end_time, :presence => true
  validate :start_time_can_not_be_in_the_past
  validate :end_time_should_be_after_start_time



  def start_time_can_not_be_in_the_past
    if self.start_time < Time.now
      errors.add(:start_time, "can't be in the past")
    end
  end

  def end_time_should_be_after_start_time
    if self.end_time < self.start_time
      errors.add(:end_time, 'should be after meeting start time')
    end
  end

  def start_date_format
    self.start_time.strftime("%-d/%-m/%y: %H:%M")
  end

  def end_date_format
    self.end_time.strftime("%-d/%-m/%y: %H:%M")
  end

  def notificate_user
    self.users.each do |u|
      UserMailer.participation_notification(u,self).deliver_now
    end
  end

end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :meeting
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :image
  has_many :members
  has_many :meetings
  has_many :booked_meetings, through: :members, source: 'meeting'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :not_include_self, -> (current_user){ where.not(id: current_user.id)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end
  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  def default_url_options
    { locale: I18n.locale }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end


end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: [:edit, :destroy]
  before_action :current_user_meeting, only: [:edit,:update,:destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id
    respond_to do |format|
      if @meeting.save
        @meeting.notificate_user
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        @meeting.notificate_user
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def current_user_meeting
      redirect_to root_path, alert: "you do not have the right to edit this meeting" unless set_meeting.creator == current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, user_ids:[])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
      @meetings = Meeting.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

  def edit
    @user = current_user
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @user = current_user
    @user.update(user_params)
    if @user.save
      flash[:notice] = 'user info has been updated'
      redirect_to root_path
    else
      flash[:alert] = 'something went wrong'
      render action:edit
    end
  end



  private

  def user_params
    params.require(:user).permit(:username,:email,:image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def meeting_participants(meeting)
    if meeting.users.present?
      "#{pluralize(meeting.users.count,'participant')} : #{meeting.users.pluck(:username).join(",")}"
    else
      "They are no participants yet"
    end
  end

  def meeting_tag(meeting)
    if meeting.creator == current_user
      "you have created this meeting"
    elsif meeting.users.include?(current_user)
      "you have been tag to participate to the meeting"
    else
      ""
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetingBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time,minute_step: 15 %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time,minute_step: 15 %>
  </div>

    <div class="field">
    <%= form.label :participatns %>
    <%= form.collection_check_boxes :user_ids, User.not_include_self(current_user), :id, :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_date_format %>
</p>

<p>
  <strong>End time:</strong>
  <%= @meeting.end_date_format %>
</p>

<p><%=meeting_participants(@meeting)%>



<% if current_user.id == @meeting.creator.id %>
  <%=render partial:'shared/user' %>
<%end%>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1 class="display-4"><%= t '.welcome' %></h1>
  <p class="lead"><%= t '.banner_paragraph' %></p>
  <hr class="my-4">
  <p><%= t '.banner_catching_paragraph' %></p>
  <%=link_to t('.create_meeting_button'),new_meeting_path, class:'btn btn-primary btn-lg' %>
</div>

<div class="container">
  <%= month_calendar events: @meetings do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>
    <div>
      <%=link_to meeting.name, meeting_path(meeting.id) %>
      <p>from <%=meeting.start_date_format%> till <%=meeting.end_date_format%></p>
      <p><%=meeting_tag(meeting)%></p>
    </div>
  <% end %>
<% end %>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%=link_to root_path do %>
    <%=image_tag "logo.png", style:"width:50px;height:50px" %>
  <%end%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" style="justify-content:space-between;" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'English', root_path(locale: :en), class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "French", root_path(locale: :fr), class:'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%if current_user %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete,class:"dropdown-item" %>
          <%else%>
            <%= link_to "Log in", new_user_session_path, class:'dropdown-item' %>
            <%= link_to 'Sign up',new_user_registration_path, class:'dropdown-item' %>
          <%end %>
        </div>
      </li>
    </ul>

    <div class="nav-item dropdown">
      <% if current_user && current_user.image.present?%>
        <%= image_tag current_user.image, class:"vatar dropdown-toggle",style:"width:50px", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <%else%>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle",style:"width:50px", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <%end%>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%=link_to "profile", edit_user_path(current_user),class:"dropdown-item" if current_user %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
    </div>
  </div>
</nav>
<br>

app/views/shared/_user.html.erb
<div class="container-fluid">
  <%=form_for @meeting ,method: :patch do |f| %>
    <%= f.collection_check_boxes :user_ids, User.not_include_self(current_user), :id, :username %>
     <%= f.submit %>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="p-5">
  <%= simple_form_for @user do |f| %>
    <%= render 'shared/errors', object: f.object %>
    <%= f.input :username,:input_html => {class:'form-control'} %>
    <%= f.input :email,:input_html => {class:'form-control'} %>
    <%= f.input :image, as: :file %>
      <br>
    <%= f.submit "submit", class: "btn btn-dark" %>
  <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-8">
      <div class="jumbotron jumbotron-fluid text-center bgc">
        <div class="container">
            <h1 class="display-4">Hi <%=current_user.username%></h1>
          <% if current_user.image.present? %>
            <%= image_tag current_user.image,style:'width:100px' %>
          <% else %>
            <p class="lead">Hi <%=current_user.username %> your picture is not uploaded yet. Don't forget to upload it</p>
          <%end%>
            <p class="lead">Your current email address is <%=current_user.email%></p>
            <%=button_to "Update info", edit_user_path, class:"btn btn-light",method: :get,remote:true %>
            <div class='form mt-5'>
            </div>
        </div>
      </div>
    </div>
    <div class="col-lg-4 background-image">
    </div>
  </div>
</div>

app/views/users/edit.js.erb
$('.form').html("<%= escape_javascript(render partial: 'users/form',locals:{ user:@user }) %>");